name: flutter_telex_error_monitor
description: A Flutter package that automatically captures application errors and exceptions at runtime and forwards them to Telex channels for real-time monitoring and debugging.
version: 0.0.2
repository: https://github.com/EmmyAnieDev/flutter_telex_error_monitor
issue_tracker: https://github.com/EmmyAnieDev/flutter_telex_error_monitor/issues
homepage: https://github.com/EmmyAnieDev/flutter_telex_error_monitor

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  http: ^1.3.0
  mockito: ^5.4.5
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# No assets needed

# Additional metadata for pub.dev
topics:
  - error-handling
  - monitoring
  - telex
  - debugging
